//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gooseman.Avro.Utility.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gooseman.Avro.Utility.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.GenericType&quot;,
        ///  &quot;aliases&quot;: [ &quot;Gooseman.Avro.Utility.Tests.Models.GenericType`1&quot; ],
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;GenericInstance&quot;,
        ///      &quot;type&quot;: &quot;{type}&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;GenericArray&quot;,
        ///      &quot;type&quot;: {
        ///        &quot;type&quot;: &quot;array&quot;,
        ///        &quot;items&quot;: &quot;{type}&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;GenericList&quot;,
        ///      &quot;type&quot;: [
        ///        {
        ///          &quot;type&quot;: &quot;array&quot;,
        ///          &quot;items&quot;: &quot;{type}&quot;
        ///        }
        ///      ]
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSchemaTemplate {
            get {
                return ResourceManager.GetString("GenericSchemaTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.NullableTypeDefaults&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Boolean&quot;,
        ///      &quot;type&quot;: &quot;boolean&quot;,
        ///      &quot;default&quot;: true
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Int&quot;,
        ///      &quot;type&quot;: &quot;int&quot;,
        ///      &quot;default&quot;: 123
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Long&quot;,
        ///      &quot;type&quot;: &quot;long&quot;,
        ///      &quot;default&quot;: 345
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Float&quot;,
        ///      &quot;type&quot;: &quot;float&quot;,
        ///      &quot;default&quot;: 567
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Double&quot;,
        ///      &quot;type&quot;: &quot;double&quot;,
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NullableTypeDefaults {
            get {
                return ResourceManager.GetString("NullableTypeDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.NullableTypeDefaults&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Boolean&quot;,
        ///      &quot;type&quot;: [&quot;null&quot;, &quot;boolean&quot;],
        ///      &quot;default&quot;: null
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Int&quot;,
        ///      &quot;type&quot;: [&quot;null&quot;, &quot;int&quot;],
        ///      &quot;default&quot;: null
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Long&quot;,
        ///      &quot;type&quot;: [&quot;null&quot;, &quot;long&quot;],
        ///      &quot;default&quot;: null
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Float&quot;,
        ///      &quot;type&quot;: [&quot;null&quot;, &quot;float&quot;],
        ///      &quot;default&quot;: null
        ///    },
        ///    {
        ///      &quot;name&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NullableTypeNullDefaults {
            get {
                return ResourceManager.GetString("NullableTypeNullDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.PrimitiveTypeDefaults&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Boolean&quot;,
        ///      &quot;type&quot;: &quot;boolean&quot;,
        ///      &quot;default&quot;: true
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Int&quot;,
        ///      &quot;type&quot;: &quot;int&quot;,
        ///      &quot;default&quot;: 123
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Long&quot;,
        ///      &quot;type&quot;: &quot;long&quot;,
        ///      &quot;default&quot;: 345
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Float&quot;,
        ///      &quot;type&quot;: &quot;float&quot;,
        ///      &quot;default&quot;: 567
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Double&quot;,
        ///      &quot;type&quot;: &quot;double&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrimitiveTypeDefaults {
            get {
                return ResourceManager.GetString("PrimitiveTypeDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;record&quot;,
        ///    &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.SalesRecord&quot;,
        ///    &quot;fields&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;Region&quot;,
        ///            &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;Country&quot;,
        ///            &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;ItemType&quot;,
        ///            &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;SalesChannel&quot;,
        ///            &quot;type&quot;: {
        ///                &quot;type&quot;: &quot;enum&quot;,
        ///                &quot;name&quot;: &quot;Gooseman.Avro.Utility. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalesRecord {
            get {
                return ResourceManager.GetString("SalesRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;SalesRecords&quot;,
        ///    &quot;type&quot;: &quot;array&quot;,
        ///    &quot;items&quot;: {
        ///        &quot;type&quot;: &quot;record&quot;,
        ///        &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.SalesRecord&quot;,
        ///      &quot;fields&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;Region&quot;,
        ///          &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Country&quot;,
        ///          &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;ItemType&quot;,
        ///          &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;SalesChannel&quot;,
        ///          &quot;type&quot;: {
        ///            &quot;type&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalesRecords {
            get {
                return ResourceManager.GetString("SalesRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.SecretMessage&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;_id&quot;,
        ///      &quot;type&quot;: &quot;string&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Message&quot;,
        ///      &quot;type&quot;: &quot;string&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string SecretMessage {
            get {
                return ResourceManager.GetString("SecretMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.ShapeBasket&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Shapes&quot;,
        ///      &quot;type&quot;: [
        ///        {
        ///          &quot;type&quot;: &quot;array&quot;,
        ///          &quot;items&quot;: [
        ///            {
        ///              &quot;type&quot;: &quot;record&quot;,
        ///              &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.Circle&quot;,
        ///              &quot;fields&quot;: [
        ///                {
        ///                  &quot;name&quot;: &quot;Name&quot;,
        ///                  &quot;type&quot;: [&quot;null&quot;, &quot;string&quot;]
        ///                },
        ///                {
        ///                  &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShapeBasket_v1_0 {
            get {
                return ResourceManager.GetString("ShapeBasket_v1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.ShapeBasket&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Shapes&quot;,
        ///      &quot;type&quot;: [
        ///        {
        ///          &quot;type&quot;: &quot;array&quot;,
        ///          &quot;items&quot;: [
        ///            {
        ///              &quot;type&quot;: &quot;record&quot;,
        ///              &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.Circle&quot;,
        ///              &quot;fields&quot;: [
        ///                {
        ///                  &quot;name&quot;: &quot;Name&quot;,
        ///                  &quot;type&quot;: [ &quot;null&quot;, &quot;string&quot; ]
        ///                },
        ///                {
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShapeBasket_v2_0 {
            get {
                return ResourceManager.GetString("ShapeBasket_v2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;record&quot;,
        ///  &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.Complex.TradeRequest&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Trade&quot;,
        ///      &quot;type&quot;: {
        ///        &quot;type&quot;: &quot;record&quot;,
        ///        &quot;name&quot;: &quot;Gooseman.Avro.Utility.Tests.Models.Complex.Vanilla&quot;,
        ///        &quot;fields&quot;: [
        ///          {
        ///            &quot;name&quot;: &quot;ExpiryDate&quot;,
        ///            &quot;type&quot;: &quot;long&quot;
        ///          },
        ///          {
        ///            &quot;name&quot;: &quot;_tenor&quot;,
        ///            &quot;type&quot;: {
        ///              &quot;type&quot;: &quot;record&quot;,
        ///              &quot;name&quot;: &quot;Gooseman.Avro.Utility.T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TradeRequest {
            get {
                return ResourceManager.GetString("TradeRequest", resourceCulture);
            }
        }
    }
}
